[project]
name = "sales-modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.2.0",
    "pandas>=3.0.0",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.46",
]
